### ISSUE TITLE
Duplicate declaration of function

### ISSUE THREAD

**Issue by tanish2k09** [GlazeOS/frameworks_base#4] opened 2017-08-15 08:45 UTC
Error in BluetoothManagerService.java

Duplicate declaration of functions 

First declaration : Line 1884
Second declaration : Line 1965

Note : Function declaration at Line 1919 is fine.

Fix is easy. Just removed function at line 1965. Only functions at 1884 and 1919 remain.

**Comment by NoelMacwan** [comment] 2017-08-15 13:15
Ops forgot to push this typo fix.
The issue isn't that, https://github.com/GlazeOS/frameworks_base/commit/7c677dea38e5ee8f4f297c0b187fe43f16ccbf2a commit was merged twice.
Pushed .
Thanks for dwelling my attention.

**Closed as completed by NoelMacwan** 2017-08-15 13:15 UTC
